/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package github.com/ariannamethod/arianna.c/tongue */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
extern size_t _GoStringLen(_GoString_ s);
extern const char *_GoStringPtr(_GoString_ s);
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 16 "tongue.go"

#include <stdlib.h>
#include <string.h>

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#if !defined(__cplusplus) || _MSVC_LANG <= 201402L
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
#include <complex>
typedef std::complex<float> GoComplex64;
typedef std::complex<double> GoComplex128;
#endif
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern int tongue_init(char* weightsPath);
extern void tongue_free(void);
extern void tongue_set_temperature_mod(float mod);
extern void tongue_set_logit_scale(float scale);
extern void tongue_set_exploratory_bias(float bias);
extern void tongue_set_temp_floor(float floor);
extern void tongue_set_rep_penalty(float penalty, int window);
extern void tongue_reset(void);
extern int tongue_generate(char* promptC, char* outputC, int maxOutputLen, int maxTokens, float temperature, float topP, char* anchorPromptC);
extern int tongue_encode(char* textC, int* idsOut, int maxTokens);
extern char* tongue_decode_token(int id);
extern int tongue_get_vocab_size(void);
extern int tongue_get_dim(void);
extern int tongue_get_seq_len(void);
extern int tongue_get_num_layers(void);

// tongue_get_logits_into copies logits into caller-provided C buffer.
// Returns number of floats written.
//
extern int tongue_get_logits_into(float* out, int maxLen);

// tongue_get_hidden_into copies hidden state into caller-provided C buffer.
// Returns number of floats written.
//
extern int tongue_get_hidden_into(float* out, int maxLen);

#ifdef __cplusplus
}
#endif
