#!/usr/bin/env bash
# admission_live_route_weighted_admission_resonance_graft_gate_smoke.sh - prepare weighted Resonance shadow graft gate.

set -euo pipefail
export LC_ALL=C

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
tmp_root="${TMPDIR:-/private/tmp}"
if [[ ! -d "$tmp_root" ]]; then tmp_root="/tmp"; fi

WORKDIR="${A2A_ADMISSION_LIVE_ROUTE_WEIGHTED_ADMISSION_RESONANCE_GRAFT_GATE_WORKDIR:-$(mktemp -d "${tmp_root%/}/arianna-live-route-weighted-admission-resonance-graft-gate.XXXXXX")}"
PREFLIGHT_WORKDIR="$WORKDIR/preflight"
GRAFT_PREFLIGHT_REPORT="$PREFLIGHT_WORKDIR/live_route_weighted_admission_resonance_graft_preflight.json"
GRAFT_GATE_REPORT="${A2A_ADMISSION_LIVE_ROUTE_WEIGHTED_ADMISSION_RESONANCE_GRAFT_GATE_REPORT:-$WORKDIR/live_route_weighted_admission_resonance_graft_gate.json}"
PREFLIGHT_LOG="$WORKDIR/weighted_admission_resonance_graft_preflight.log"
GRAFT_GATE_LOG="$WORKDIR/weighted_admission_resonance_graft_gate.log"

die() {
    echo "[admission-live-route-weighted-admission-resonance-graft-gate-smoke] FAIL: $*" >&2
    if [[ -f "$PREFLIGHT_LOG" ]]; then
        tail -n 500 "$PREFLIGHT_LOG" >&2 || true
    fi
    if [[ -f "$GRAFT_GATE_LOG" ]]; then
        tail -n 220 "$GRAFT_GATE_LOG" >&2 || true
    fi
    exit 1
}

require_grep() {
    local pattern="$1"
    local file="$2"
    local label="$3"
    if ! grep -q "$pattern" "$file"; then
        die "$label missing in $file"
    fi
}

mkdir -p "$WORKDIR"

if ! A2A_ADMISSION_LIVE_ROUTE_WEIGHTED_ADMISSION_RESONANCE_GRAFT_PREFLIGHT_WORKDIR="$PREFLIGHT_WORKDIR" \
    A2A_ADMISSION_LIVE_ROUTE_WEIGHTED_ADMISSION_RESONANCE_GRAFT_PREFLIGHT_REPORT="$GRAFT_PREFLIGHT_REPORT" \
    bash "$ROOT/tools/admission_live_route_weighted_admission_resonance_graft_preflight_smoke.sh" >"$PREFLIGHT_LOG" 2>&1; then
    die "weighted admission resonance graft preflight producer failed"
fi

[[ -s "$GRAFT_PREFLIGHT_REPORT" ]] || die "weighted admission resonance graft preflight report not written: $GRAFT_PREFLIGHT_REPORT"

if ! bash "$ROOT/tools/admission_live_route_weighted_admission_resonance_graft_gate.sh" "$GRAFT_PREFLIGHT_REPORT" "$GRAFT_GATE_REPORT" >"$GRAFT_GATE_LOG" 2>&1; then
    die "weighted admission resonance graft gate rejected preflight report"
fi

[[ -s "$GRAFT_GATE_REPORT" ]] || die "weighted admission resonance graft gate report not written: $GRAFT_GATE_REPORT"

require_grep '"schema": "arianna.live_route_weighted_admission_resonance_graft_gate.v1"' "$GRAFT_GATE_REPORT" "resonance-graft-gate schema"
require_grep '"status": "shadow_graft_gate_ready_dry_run"' "$GRAFT_GATE_REPORT" "resonance-graft-gate status"
require_grep '"target": "resonance"' "$GRAFT_GATE_REPORT" "resonance-graft-gate target"
require_grep '"target_kind": "weighted_internal_world_shadow_graft_gate"' "$GRAFT_GATE_REPORT" "resonance-graft-gate target kind"
require_grep '"target_mode": "receipt_only_closed_gate_dry_run"' "$GRAFT_GATE_REPORT" "resonance-graft-gate target mode"
require_grep '"action": "gate_weighted_resonance_shadow_graft_dry_run"' "$GRAFT_GATE_REPORT" "resonance-graft-gate action"
require_grep '"weighted_admission_resonance_graft_gate_ready": true' "$GRAFT_GATE_REPORT" "graft-gate ready flag"
require_grep '"weighted_admission_resonance_graft_preflight_consumed": true' "$GRAFT_GATE_REPORT" "graft-preflight consumed flag"
require_grep '"weighted_admission_resonance_graft_preflight_required": true' "$GRAFT_GATE_REPORT" "graft-preflight required flag"
require_grep '"next_step_blocked_without_resonance_graft_gate": true' "$GRAFT_GATE_REPORT" "next-step block flag"
require_grep '"weighted_admission_resonance_graft_gate_id": "weighted-resonance-graft-gate-id-' "$GRAFT_GATE_REPORT" "graft-gate id"
require_grep '"receipt_shape": "weighted_resonance_shadow_graft_gate_contract"' "$GRAFT_GATE_REPORT" "receipt shape"
require_grep '"gate_kind": "shadow_graft_gate"' "$GRAFT_GATE_REPORT" "gate kind"
require_grep '"gate_mode": "no_mutation_gate"' "$GRAFT_GATE_REPORT" "gate mode"
require_grep '"gate_stage": "pre_live_graft_gate"' "$GRAFT_GATE_REPORT" "gate stage"
require_grep '"causal_id": "weighted-resonance-graft-gate-causal-' "$GRAFT_GATE_REPORT" "causal id"
require_grep '"gate_hash": "weighted-resonance-graft-gate-' "$GRAFT_GATE_REPORT" "gate hash"
require_grep '"read_back_hash": "weighted-resonance-graft-gate-read-' "$GRAFT_GATE_REPORT" "read-back hash"
require_grep '"preflight_verified": true' "$GRAFT_GATE_REPORT" "preflight verification"
require_grep '"boundary_verified": true' "$GRAFT_GATE_REPORT" "boundary verification"
require_grep '"observation_verified": true' "$GRAFT_GATE_REPORT" "observation verification"
require_grep '"receiver_verified": true' "$GRAFT_GATE_REPORT" "receiver verification"
require_grep '"intent_verified": true' "$GRAFT_GATE_REPORT" "intent verification"
require_grep '"final_gate_verified": true' "$GRAFT_GATE_REPORT" "final-gate verification"
require_grep '"seal_verified": true' "$GRAFT_GATE_REPORT" "seal verification"
require_grep '"permit_verified": true' "$GRAFT_GATE_REPORT" "permit verification"
require_grep '"authority_verified": true' "$GRAFT_GATE_REPORT" "authority verification"
require_grep '"admission_required": true' "$GRAFT_GATE_REPORT" "admission requirement"
require_grep '"shadow_only": true' "$GRAFT_GATE_REPORT" "shadow flag"
require_grep '"graft_allowed": false' "$GRAFT_GATE_REPORT" "graft guard"
require_grep '"dry_run_only": true' "$GRAFT_GATE_REPORT" "dry-run flag"
require_grep '"live_ready": true' "$GRAFT_GATE_REPORT" "live-ready flag"
require_grep '"raw_dream_text_allowed": false' "$GRAFT_GATE_REPORT" "raw dream text allow guard"
require_grep '"raw_dream_text_observed": false' "$GRAFT_GATE_REPORT" "raw dream text observe guard"
require_grep '"raw_dream_text_forwarded": false' "$GRAFT_GATE_REPORT" "raw dream text forward guard"
require_grep '"janus_surface_allowed": false' "$GRAFT_GATE_REPORT" "Janus surface guard"
require_grep '"cooc_learning_allowed": false' "$GRAFT_GATE_REPORT" "cooc guard"
require_grep '"delta_harvest_allowed": false' "$GRAFT_GATE_REPORT" "delta guard"
require_grep '"body_mutation_allowed": false' "$GRAFT_GATE_REPORT" "body mutation guard"
require_grep '"rollback_required": true' "$GRAFT_GATE_REPORT" "rollback requirement"
require_grep '"source_schema": "arianna.live_route_weighted_admission_resonance_graft_preflight.v1"' "$GRAFT_GATE_REPORT" "source preflight schema"
require_grep '"source_status": "shadow_graft_preflight_ready_dry_run"' "$GRAFT_GATE_REPORT" "source preflight status"
require_grep '"source_target": "resonance"' "$GRAFT_GATE_REPORT" "source preflight target"
require_grep '"source_weighted_admission_resonance_graft_preflight_id": "weighted-resonance-graft-preflight-id-' "$GRAFT_GATE_REPORT" "source preflight id"
require_grep '"source_weighted_admission_resonance_graft_preflight_ready": true' "$GRAFT_GATE_REPORT" "source preflight ready"
require_grep '"source_weighted_admission_resonance_graft_preflight_causal_id": "weighted-resonance-graft-preflight-causal-' "$GRAFT_GATE_REPORT" "source preflight causal"
require_grep '"source_weighted_admission_resonance_graft_preflight_hash": "weighted-resonance-graft-preflight-' "$GRAFT_GATE_REPORT" "source preflight hash"
require_grep '"source_weighted_admission_resonance_graft_preflight_read_back_hash": "weighted-resonance-graft-preflight-read-' "$GRAFT_GATE_REPORT" "source preflight read-back"
require_grep '"source_preflight_action": "prepare_weighted_resonance_shadow_graft_preflight_dry_run"' "$GRAFT_GATE_REPORT" "source preflight action"
require_grep '"source_preflight_receipt_shape": "weighted_resonance_shadow_graft_preflight_contract"' "$GRAFT_GATE_REPORT" "source preflight receipt"
require_grep '"source_preflight_kind": "shadow_graft_preflight"' "$GRAFT_GATE_REPORT" "source preflight kind"
require_grep '"source_preflight_mode": "no_mutation_preflight"' "$GRAFT_GATE_REPORT" "source preflight mode"
require_grep '"source_preflight_stage": "pre_live_graft_admission"' "$GRAFT_GATE_REPORT" "source preflight stage"
require_grep '"source_preflight_shadow_only": true' "$GRAFT_GATE_REPORT" "source preflight shadow"
require_grep '"source_preflight_graft_allowed": false' "$GRAFT_GATE_REPORT" "source preflight graft guard"
require_grep '"source_preflight_dry_run_only": true' "$GRAFT_GATE_REPORT" "source preflight dry-run"
require_grep '"source_preflight_live_ready": true' "$GRAFT_GATE_REPORT" "source preflight live-ready"
require_grep '"source_preflight_raw_dream_text_allowed": false' "$GRAFT_GATE_REPORT" "source preflight raw guard"
require_grep '"source_preflight_janus_surface_allowed": false' "$GRAFT_GATE_REPORT" "source preflight Janus guard"
require_grep '"source_preflight_cooc_learning_allowed": false' "$GRAFT_GATE_REPORT" "source preflight cooc guard"
require_grep '"source_preflight_delta_harvest_allowed": false' "$GRAFT_GATE_REPORT" "source preflight delta guard"
require_grep '"source_preflight_body_mutation_allowed": false' "$GRAFT_GATE_REPORT" "source preflight body mutation guard"
require_grep '"source_preflight_rollback_required": true' "$GRAFT_GATE_REPORT" "source preflight rollback"
require_grep '"source_graft_boundary_schema": "arianna.live_route_weighted_admission_resonance_graft_boundary.v1"' "$GRAFT_GATE_REPORT" "source graft boundary schema"
require_grep '"source_graft_boundary_status": "shadow_graft_boundary_declared_dry_run"' "$GRAFT_GATE_REPORT" "source graft boundary status"
require_grep '"source_graft_boundary_target": "resonance"' "$GRAFT_GATE_REPORT" "source graft boundary target"
require_grep '"source_graft_boundary_report": "' "$GRAFT_GATE_REPORT" "source graft boundary report"
require_grep '"source_weighted_admission_resonance_graft_boundary_id": "weighted-resonance-graft-boundary-id-' "$GRAFT_GATE_REPORT" "source boundary id"
require_grep '"source_weighted_admission_resonance_graft_boundary_ready": true' "$GRAFT_GATE_REPORT" "source boundary ready"
require_grep '"source_weighted_admission_resonance_graft_boundary_causal_id": "weighted-resonance-graft-boundary-causal-' "$GRAFT_GATE_REPORT" "source boundary causal"
require_grep '"source_weighted_admission_resonance_graft_boundary_hash": "weighted-resonance-graft-boundary-' "$GRAFT_GATE_REPORT" "source boundary hash"
require_grep '"source_weighted_admission_resonance_graft_boundary_read_back_hash": "weighted-resonance-graft-boundary-read-' "$GRAFT_GATE_REPORT" "source boundary read-back"
require_grep '"source_boundary_action": "declare_weighted_resonance_shadow_graft_boundary_dry_run"' "$GRAFT_GATE_REPORT" "source boundary action"
require_grep '"source_boundary_receipt_shape": "weighted_resonance_observation_shadow_graft_boundary"' "$GRAFT_GATE_REPORT" "source boundary receipt"
require_grep '"source_boundary_kind": "shadow_graft_boundary"' "$GRAFT_GATE_REPORT" "source boundary kind"
require_grep '"source_boundary_mode": "no_mutation_receipt"' "$GRAFT_GATE_REPORT" "source boundary mode"
require_grep '"source_boundary_stage": "pre_live_graft"' "$GRAFT_GATE_REPORT" "source boundary stage"
require_grep '"source_boundary_shadow_only": true' "$GRAFT_GATE_REPORT" "source boundary shadow"
require_grep '"source_boundary_graft_allowed": false' "$GRAFT_GATE_REPORT" "source boundary graft guard"
require_grep '"source_boundary_dry_run_only": true' "$GRAFT_GATE_REPORT" "source boundary dry-run"
require_grep '"source_boundary_live_ready": true' "$GRAFT_GATE_REPORT" "source boundary live-ready"
require_grep '"source_boundary_raw_dream_text_allowed": false' "$GRAFT_GATE_REPORT" "source boundary raw guard"
require_grep '"source_boundary_janus_surface_allowed": false' "$GRAFT_GATE_REPORT" "source boundary Janus guard"
require_grep '"source_boundary_cooc_learning_allowed": false' "$GRAFT_GATE_REPORT" "source boundary cooc guard"
require_grep '"source_boundary_delta_harvest_allowed": false' "$GRAFT_GATE_REPORT" "source boundary delta guard"
require_grep '"source_boundary_body_mutation_allowed": false' "$GRAFT_GATE_REPORT" "source boundary body mutation guard"
require_grep '"source_boundary_rollback_required": true' "$GRAFT_GATE_REPORT" "source boundary rollback"
require_grep '"source_observation_schema": "arianna.live_route_weighted_admission_resonance_observation.v1"' "$GRAFT_GATE_REPORT" "source observation schema"
require_grep '"source_observation_status": "observation_recorded_dry_run"' "$GRAFT_GATE_REPORT" "source observation status"
require_grep '"source_observation_target": "resonance"' "$GRAFT_GATE_REPORT" "source observation target"
require_grep '"source_weighted_admission_resonance_observation_id": "weighted-resonance-observation-' "$GRAFT_GATE_REPORT" "source observation id"
require_grep '"source_weighted_admission_resonance_observation_ready": true' "$GRAFT_GATE_REPORT" "source observation-ready flag"
require_grep '"source_weighted_admission_resonance_observation_causal_id": "weighted-resonance-observation-causal-' "$GRAFT_GATE_REPORT" "source observation causal id"
require_grep '"source_weighted_admission_resonance_observation_append_hash": "weighted-resonance-observation-append-' "$GRAFT_GATE_REPORT" "source observation append hash"
require_grep '"source_weighted_admission_resonance_observation_read_back_hash": "weighted-resonance-observation-read-' "$GRAFT_GATE_REPORT" "source observation read-back hash"
require_grep '"source_observer": "resonance"' "$GRAFT_GATE_REPORT" "source observer"
require_grep '"source_observer_kind": "internal_world"' "$GRAFT_GATE_REPORT" "source observer kind"
require_grep '"source_observation_kind": "weighted_receiver_state_proof"' "$GRAFT_GATE_REPORT" "source observation kind"
require_grep '"source_observation_mode": "sealed_metadata_observation"' "$GRAFT_GATE_REPORT" "source observation mode"
require_grep '"source_append_only": true' "$GRAFT_GATE_REPORT" "source append-only flag"
require_grep '"source_read_back": true' "$GRAFT_GATE_REPORT" "source read-back flag"
require_grep '"source_receipt_verified": true' "$GRAFT_GATE_REPORT" "source receipt flag"
require_grep '"source_dry_run_only": true' "$GRAFT_GATE_REPORT" "source dry-run flag"
require_grep '"source_observation_raw_dream_text_observed": false' "$GRAFT_GATE_REPORT" "source observation raw observe guard"
require_grep '"source_observation_body_mutation_allowed": false' "$GRAFT_GATE_REPORT" "source observation body guard"
require_grep '"source_observation_rollback_required": true' "$GRAFT_GATE_REPORT" "source observation rollback"
require_grep '"source_resonance_receiver_report": "' "$GRAFT_GATE_REPORT" "source receiver report"
require_grep '"source_resonance_intent_report": "' "$GRAFT_GATE_REPORT" "source intent report"
require_grep '"source_final_gate_report": "' "$GRAFT_GATE_REPORT" "source final gate report"
require_grep '"source_weighted_admission_resonance_receiver_id": "weighted-resonance-receiver-' "$GRAFT_GATE_REPORT" "source receiver id"
require_grep '"source_weighted_admission_resonance_receiver_ready": true' "$GRAFT_GATE_REPORT" "source receiver-ready flag"
require_grep '"source_weighted_admission_resonance_receiver_causal_id": "weighted-resonance-receiver-causal-' "$GRAFT_GATE_REPORT" "source receiver causal id"
require_grep '"source_receiver_pre_state_hash": "weighted-resonance-receiver-pre-' "$GRAFT_GATE_REPORT" "source receiver pre-state hash"
require_grep '"source_receiver_post_state_hash": "weighted-resonance-receiver-post-' "$GRAFT_GATE_REPORT" "source receiver post-state hash"
require_grep '"source_receiver_state_delta_hash": "weighted-resonance-receiver-delta-' "$GRAFT_GATE_REPORT" "source receiver state-delta hash"
require_grep '"source_weighted_admission_resonance_intent_consumed": true' "$GRAFT_GATE_REPORT" "source intent consumed flag"
require_grep '"source_weighted_admission_resonance_intent_required": true' "$GRAFT_GATE_REPORT" "source intent required flag"
require_grep '"source_weighted_admission_resonance_intent_ready": true' "$GRAFT_GATE_REPORT" "source intent-ready flag"
require_grep '"source_weighted_admission_final_gate_ready": true' "$GRAFT_GATE_REPORT" "source final-gate-ready flag"
require_grep '"source_weighted_admission_seal_ready": true' "$GRAFT_GATE_REPORT" "source seal-ready flag"
require_grep '"source_weighted_admission_permit_ready": true' "$GRAFT_GATE_REPORT" "source permit-ready flag"
require_grep '"source_weighted_admission_authority_consumed": true' "$GRAFT_GATE_REPORT" "source authority consumed flag"
require_grep '"source_weighted_admission_authority_required": true' "$GRAFT_GATE_REPORT" "source authority required flag"
require_grep '"source_raw_dream_text_allowed": false' "$GRAFT_GATE_REPORT" "source raw guard"
require_grep '"source_raw_dream_text_observed": false' "$GRAFT_GATE_REPORT" "source raw observe guard"
require_grep '"source_raw_dream_text_forwarded": false' "$GRAFT_GATE_REPORT" "source raw forward guard"
require_grep '"source_janus_surface_allowed": false' "$GRAFT_GATE_REPORT" "source Janus guard"
require_grep '"source_cooc_learning_allowed": false' "$GRAFT_GATE_REPORT" "source cooc guard"
require_grep '"source_delta_harvest_allowed": false' "$GRAFT_GATE_REPORT" "source delta guard"
require_grep '"source_body_mutation_allowed": false' "$GRAFT_GATE_REPORT" "source body mutation guard"
require_grep '"source_rollback_required": true' "$GRAFT_GATE_REPORT" "source rollback requirement"
require_grep '"source_pre_state_hash_required": true' "$GRAFT_GATE_REPORT" "source pre-state requirement"
require_grep '"source_post_state_hash_required": true' "$GRAFT_GATE_REPORT" "source post-state requirement"
require_grep '"body_smoke_weighted": true' "$GRAFT_GATE_REPORT" "weighted body-smoke flag"
require_grep '"nano_direct_runner": true' "$GRAFT_GATE_REPORT" "nano direct runner flag"
require_grep '"nano_direct_final_gate": true' "$GRAFT_GATE_REPORT" "nano final-gate flag"
require_grep '"resonance_graft_admission_proof": true' "$GRAFT_GATE_REPORT" "resonance graft proof flag"
require_grep '"boundary_report_full_chain": true' "$GRAFT_GATE_REPORT" "boundary full-chain flag"
require_grep '"source_authority_granted": false' "$GRAFT_GATE_REPORT" "closed source authority flag"
require_grep '"authority_granted": false' "$GRAFT_GATE_REPORT" "closed authority flag"
require_grep '"contracts_ready": false' "$GRAFT_GATE_REPORT" "closed contracts flag"
require_grep '"write_allowed": false' "$GRAFT_GATE_REPORT" "closed writer flag"
require_grep '"admission_allowed": false' "$GRAFT_GATE_REPORT" "closed admission flag"
require_grep '"live_admission_enabled": false' "$GRAFT_GATE_REPORT" "closed live flag"
require_grep '"mutates_state": false' "$GRAFT_GATE_REPORT" "non-mutation flag"
require_grep '"body_target": "none"' "$GRAFT_GATE_REPORT" "body target"
require_grep '"passed": true' "$GRAFT_GATE_REPORT" "resonance-graft-gate pass flag"
require_grep '\[admission-live-route-weighted-admission-resonance-graft-gate\] pass:' "$GRAFT_GATE_LOG" "resonance-graft-gate pass line"

echo "[admission-live-route-weighted-admission-resonance-graft-gate-smoke] pass: resonance_graft_preflight_report=$GRAFT_PREFLIGHT_REPORT resonance_graft_gate_report=$GRAFT_GATE_REPORT"
