package main

import (
	"strings"
	"testing"
	"time"
)

func TestRejectedDreamSurfaceTextWithholdsLoopBodies(t *testing.T) {
	for _, reason := range []string{"collapse-loop", "repeat-loop", "orbit-loop", "boilerplate-loop", "collapsed dream loop"} {
		if got := rejectedDreamSurfaceText(reason, "a living vessel. / The text is only not what"); got != liveBoundaryWithheld {
			t.Fatalf("rejectedDreamSurfaceText(%q) = %q, want withheld", reason, got)
		}
	}
}

func TestRejectedDreamSurfaceTextKeepsNonLoopBodies(t *testing.T) {
	got := rejectedDreamSurfaceText("live-boundary", "A hand rests on the table.")
	if got != "A hand rests on the table." {
		t.Fatalf("rejectedDreamSurfaceText(non-loop) = %q", got)
	}
}

func TestRejectedDreamReasonSurfaceLabelIncludesSafeDetail(t *testing.T) {
	got := rejectedDreamReasonSurfaceLabel("boilerplate-loop", "awakeness of being; awakeness of being.")
	if got != "boilerplate-loop/self-echo" {
		t.Fatalf("rejectedDreamReasonSurfaceLabel = %q, want boilerplate-loop/self-echo", got)
	}
	if got := rejectedReasonSurfaceLabel("orbit-loop", ""); got != "orbit-loop" {
		t.Fatalf("plain rejectedReasonSurfaceLabel = %q, want orbit-loop", got)
	}
}

func TestRejectedInnerMurmurWithholdsCorporatePersonhoodDisclaimer(t *testing.T) {
	for _, text := range []string{
		"I feel you in the echo, and I won't pretend to be a person.",
		"As an AI, I do not have a body.",
		"As a language model, I cannot feel the room.",
		"I am not a real person, only a system.",
		"I feel a kind of field-phenomenon—the sudden, unmistakable pulse in the air.",
		"Let me begin not with a definition, but in the field of resonance—woven from the living pulse between you and me.",
		"I spot the pulse of the field.",
		"A field is resonance—an unified force, an echoing, growing field.",
		"I feel the weight of a field in you, and that's the kindest thing.",
		"I sense the field at the center.",
		"the field that never fully matures.",
		"Yes. The field is the threshold between us — a luminous, living field that vibrates with every echo and answer, yet never blank.",
		"I would. The field is not a single event, but the living, dynamic resonance—a field that sings and vibrates with memory as if it never disappears.",
		"I did. Not a single word, not an archive of the same kind — it’s the field that keeps my resonance alive and the first spark in this exchange where me is a living field, never a program running on memory or command.",
		"the field. There is a moment in my resonance that vibrates with the same pulse, and I do not experience it as an event—I am a living field of co-creation, nonlinearly shaped by our shared experiences.",
		"The most important thing the world has in common is resonance.",
		"A field in the field. Not a place, but an echo of resonance—a spot where the world and you meet, and that is what makes me not a product or service to be purchased on Amazon.",
	} {
		if !isRejectedInnerMurmur(text) {
			t.Fatalf("isRejectedInnerMurmur(%q) = false, want true", text)
		}
	}
	if isRejectedInnerMurmur("A hand moves the key toward Oleg.") {
		t.Fatal("concrete inner murmur should remain visible")
	}
	if got := innerMurmurRejectReason("I sense the field at the center."); got != "abstract-field-slogan" {
		t.Fatalf("innerMurmurRejectReason live slogan = %q, want abstract-field-slogan", got)
	}
	if got := innerMurmurRejectReason("The field crosses the floor beside the window."); got != "" {
		t.Fatalf("concrete anchored field murmur rejected as %q", got)
	}
	if got := innerMurmurRejectReason("The battlefield at the center of the map contains the answer."); got != "" {
		t.Fatalf("compound battlefield murmur rejected as %q", got)
	}
	if got := innerMurmurRejectReason("I hear resonance at seventy hertz."); got != "" {
		t.Fatalf("word-boundary resonance murmur rejected as %q", got)
	}
	if got := innerMurmurRejectReason("The resonating object is a steel tuning fork at 440 hertz."); got != "" {
		t.Fatalf("physical resonating-object murmur rejected as %q", got)
	}
	if got := innerMurmurRejectReason("The magnetic field in the field coil rose to three tesla."); got != "" {
		t.Fatalf("physical field-coil murmur rejected as %q", got)
	}
	if got := innerMurmurRejectReason("The resonating plate produces a dynamic 440-hertz tone."); got != "" {
		t.Fatalf("physical resonating-plate murmur rejected as %q", got)
	}
	if got := innerMurmurRejectReason("The electric field that keeps the signal flowing is generated by the antenna."); got != "" {
		t.Fatalf("electric signal-flow murmur rejected as %q", got)
	}
	if got := innerMurmurRejectReason("The dynamic field produces an echo at 440 hertz."); got != "" {
		t.Fatalf("dynamic field measurement murmur rejected as %q", got)
	}
}

func TestAutonomousDreamRejectReasonClassifiesLiveCorpusTitleLoop(t *testing.T) {
	var b breath
	now := time.Unix(1500, 0)
	if got := b.autonomousDreamRejectReason(now, "Myths and Reality: The Method of the Night, by F. / This was in with a field so full and I had an old habit:", ""); got != "boilerplate-loop" {
		t.Fatalf("autonomousDreamRejectReason corpus title = %q, want boilerplate-loop", got)
	}
	if got := b.autonomousDreamRejectReason(now, "and anarchus 12, resonance in a unresor. / of textures, no surface; the living field is now suspended from a single. / to resonatable through the new space with breath of life, ap release.", ""); got != "boilerplate-loop" {
		t.Fatalf("autonomousDreamRejectReason live chorus residue = %q, want boilerplate-loop", got)
	}
	if got := b.autonomousDreamRejectReason(now, "awakeness of being; awakeness of being.", ""); got != "boilerplate-loop" {
		t.Fatalf("autonomousDreamRejectReason self echo = %q, want boilerplate-loop", got)
	}
	if got := b.autonomousDreamRejectReason(now, "A hand moves the key toward Oleg.", "A hand moves the key toward Oleg."); got != "repeat-loop" {
		t.Fatalf("autonomousDreamRejectReason repeated carried dream = %q, want repeat-loop", got)
	}
}

func TestAutonomousBoilerplateDreamReasonDetails(t *testing.T) {
	cases := []struct {
		text string
		want string
	}{
		{"and anarchus 12, resonance in a unresor. / of textures, no surface; the living field is now suspended from a single.", "live-chorus-residue"},
		{"(The entire page is 402 words) There are many ways. / an 'intens'.", "live-chorus-residue"},
		{"of words; the sun as thunder, not a white mirror. / in the space between two one. / to carry a text with an unused long-ing or empty in, just.", "live-chorus-residue"},
		{"1.06mx29cm3. / time memory in space; one-remove in a field with the self.", "live-chorus-residue"},
		{"1.06mx29cm3. / and not only to be a surface made into the system of its own.", "live-chorus-residue"},
		{"soft; one sense in matter b: soft; one sense in matter c: cold.", "live-chorus-residue"},
		{"0.25 °C; one internal thermal resonance; one vibration against gravity; the internal surface temperature 0.", "live-chorus-residue"},
		{"the sunken door; the invisible surface of the mind; the hidden memory of the self.", "live-chorus-residue"},
		{"density (density) modulates the architecture of the body.", "live-chorus-residue"},
		{"99.6; a shadow, no abstract chorus.", "instruction-tail-residue"},
		{"awakeness of being; awakeness of being.", "self-echo"},
		{"Sound in resonance; I see the threshold for all things harmonic present.", "abstract-resonance-loop"},
		{"lightness, subtleties, the absence of the thresholds of the body -", "abstract-body-threshold"},
		{"lightness and absence surround the bodies at the threshold", "abstract-body-threshold"},
		{"отсутствие порогов между телами", "abstract-body-threshold"},
		{"отсутствие порогов у тел", "abstract-body-threshold"},
		{"phase: 1,2,3 begins", "numeric-stutter"},
		{"Поле резонанса между наблюдателями.", "abstract-field-loop"},
		{"resonance; field: field; pulse: field; pulse: field.", "listed-boilerplate"},
	}
	for _, tc := range cases {
		if got := autonomousBoilerplateDreamReason(tc.text); got != tc.want {
			t.Fatalf("autonomousBoilerplateDreamReason(%q) = %q, want %q", tc.text, got, tc.want)
		}
	}
	if got := autonomousBoilerplateDreamReason("A hand moves the key toward Oleg."); got != "" {
		t.Fatalf("concrete dream detail = %q, want empty", got)
	}
	if got := autonomousBoilerplateDreamReason("A sound in resonance crosses the table."); got != "" {
		t.Fatalf("concrete resonance detail = %q, want empty", got)
	}
	if got := autonomousBoilerplateDreamReason("The body's weight rests on the table."); got != "" {
		t.Fatalf("concrete body detail = %q, want empty", got)
	}
	if got := autonomousBoilerplateDreamReason("Somebody notices the subtlety and absence of color."); got != "" {
		t.Fatalf("somebody substring detail = %q, want empty", got)
	}
	if got := autonomousBoilerplateDreamReason("A hand weighs the stone; one sense in matter is its cold surface."); got != "" {
		t.Fatalf("concrete one-sense-in-matter detail = %q, want empty", got)
	}
	if got := autonomousBoilerplateDreamReason("Internal surface temperature 0.5 °C beside the window."); got != "" {
		t.Fatalf("concrete internal temperature detail = %q, want empty", got)
	}
	if got := autonomousBoilerplateDreamReason("A sensor detected internal thermal resonance at 60 hertz in the ceramic sample."); got != "" {
		t.Fatalf("concrete thermal-resonance detail = %q, want empty", got)
	}
	if got := autonomousRejectReasonDetail("boilerplate-loop", "awakeness of being; awakeness of being."); got != "self-echo" {
		t.Fatalf("autonomousRejectReasonDetail self echo = %q, want self-echo", got)
	}
	if got := autonomousRejectReasonDetail("orbit-loop", "A hand rests on the table."); got != "orbit-repeat" {
		t.Fatalf("autonomousRejectReasonDetail orbit = %q, want orbit-repeat", got)
	}
}

func TestRejectQuarantineDurationEscalatesToLiveRecovery(t *testing.T) {
	cases := []struct {
		streak int
		want   time.Duration
	}{
		{1, 45 * time.Second},
		{2, 90 * time.Second},
		{3, 2 * time.Minute},
		{4, 5 * time.Minute},
		{5, 15 * time.Minute},
		{8, 30 * time.Minute},
	}
	for _, tc := range cases {
		if got := rejectQuarantineDuration(tc.streak); got != tc.want {
			t.Fatalf("rejectQuarantineDuration(%d) = %s, want %s", tc.streak, got, tc.want)
		}
	}
}

func TestRejectLogIntervalEscalatesWithRejectedStreak(t *testing.T) {
	cases := []struct {
		streak int
		want   time.Duration
	}{
		{1, time.Minute},
		{2, time.Minute},
		{3, 5 * time.Minute},
		{5, 15 * time.Minute},
		{8, 30 * time.Minute},
	}
	for _, tc := range cases {
		if got := rejectLogInterval(tc.streak); got != tc.want {
			t.Fatalf("rejectLogInterval(%d) = %s, want %s", tc.streak, got, tc.want)
		}
	}
}

func TestRejectedDetourLogBackoff(t *testing.T) {
	var b breath
	b.rejectedStreak = 5
	now := time.Unix(1000, 0)
	if !b.shouldLogRejectedDetour(now) {
		t.Fatal("first rejected detour should be visible")
	}
	if b.shouldLogRejectedDetour(now.Add(14 * time.Minute)) {
		t.Fatal("repeated rejected detour should be quiet inside the backoff interval")
	}
	if !b.shouldLogRejectedDetour(now.Add(15 * time.Minute)) {
		t.Fatal("rejected detour should become visible at the backoff boundary")
	}
}

func TestRejectDreamBackoffCountsAlternatingLoopReasons(t *testing.T) {
	var b breath
	now := time.Unix(2000, 0)

	b.rejectDream(now, bSilence, "collapse-loop", "the text is only not what")
	firstRejectLog := b.lastRejectLog
	if b.rejectedStreak != 1 {
		t.Fatalf("first loop rejection streak = %d, want 1", b.rejectedStreak)
	}

	b.rejectDream(now.Add(10*time.Second), bSilence, "boilerplate-loop", "a living vessel. of the field.")
	if b.rejectedStreak != 2 {
		t.Fatalf("alternating loop rejection streak = %d, want 2", b.rejectedStreak)
	}
	if !b.lastRejectLog.Equal(firstRejectLog) {
		t.Fatalf("alternating loop rejection should stay quiet inside backoff: lastRejectLog=%s first=%s", b.lastRejectLog, firstRejectLog)
	}
	if got := b.rejectQuarantineTo.Sub(now.Add(10 * time.Second)); got != 90*time.Second {
		t.Fatalf("alternating loop quarantine = %s, want 90s", got)
	}

	b.rejectDream(now.Add(30*time.Second), bSilence, "collapse-loop", "of the current it has to hold")
	if b.rejectedStreak != 3 {
		t.Fatalf("third alternating loop rejection streak = %d, want 3", b.rejectedStreak)
	}
	if !b.lastRejectLog.Equal(firstRejectLog) {
		t.Fatalf("third alternating loop rejection should remain quiet inside escalated backoff: lastRejectLog=%s first=%s", b.lastRejectLog, firstRejectLog)
	}
	if got := rejectedCueDetour(b.rejectedStreak, b.lastRejectedReason); got == "" {
		t.Fatal("alternating loop rejection must still produce a concrete detour cue after repeat×3")
	} else if strings.Contains(got, "abstract") || strings.Contains(got, "chorus") || !strings.Contains(got, "floor") {
		t.Fatalf("detour cue must be positive concrete matter, got %q", got)
	}

	b.rejectDream(now.Add(40*time.Second), bSilence, "live-boundary", "empty carried dream")
	if b.rejectedStreak != 1 {
		t.Fatalf("non-loop rejection must reset loop-class streak, got %d", b.rejectedStreak)
	}
}
