/*
 * External Brain 30M - Model Configuration
 * Auto-generated by export.py
 */

#ifndef EXTERNAL_BRAIN_CONFIG_H
#define EXTERNAL_BRAIN_CONFIG_H

#define EB_DIM 512
#define EB_N_LAYERS 10
#define EB_N_HEADS 8
#define EB_N_KV_HEADS 4
#define EB_HEAD_DIM 64
#define EB_HIDDEN_DIM 1408
#define EB_VOCAB_SIZE 80
#define EB_MAX_SEQ_LEN 512
#define EB_ROPE_THETA 10000.0f
#define EB_NORM_EPS 1e-5f

#endif // EXTERNAL_BRAIN_CONFIG_H
